doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm: # ❌ Disable this block if not using Doctrine ORM
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        # mappings:
        #     App:
        #         is_bundle: false
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
